version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DB_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d/db_init.sql  
    networks:
      - app-network

  backend:
    build:
      context: ./BE
      dockerfile: Dockerfile
    container_name: be
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/${MYSQL_DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - AWS_ACCESSKEY=${AWS_ACCESS_KEY}
      - AWS_SECRETKEY=${AWS_SECRET_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - GOOGLE_CLIENTID=${GOOGLE_CLIENT_ID}
      - MOMO_RETURN_URL=${MOMO_RETURN_URL}
      - MOMO_NOTIFY_URL=${MOMO_NOTIFY_URL}
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network
    restart: on-failure

  frontend:
    build:
      context: ./FE/e-learning
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
    container_name: fe
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - app-network


volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
