server:
  port: 8080
  servlet:
    context-path: /elearning/api

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;instanceName=SQLEXPRESS;databaseName=E-LearningTest;encrypt=true;trustServerCertificate=true
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
jwt:
  secret-key: your-super-secret-key-12345678901234567890123456789012
  access-time: 300000
  refresh-time: 604800000
